Fix/assembly manual
rt-net/stack-chan pull request #12
Opened 2024-06-11 05:39 UTC by KuraZuzu

# What does this implement/fix?

組み立てマニュアルの品質を向上。

# Does this close any currently open issues?

Issue https://github.com/rt-net/stack-chan/issues/11 をクローズします。

# How has this been tested?

アールティ社内でレビューしました。

# Any other comments?

# Checklists

- [ ]  I have read the CONTRIBUTING guidelines.
    
    - If there is no guideline in the repository, [rt-net organization's guideline](https://github.com/rt-net/.github/blob/master/CONTRIBUTING.md) applies.
- [ ]  I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same change.

2024-06-11 06:50 UTC, meganetaaan requested changes
軽微な指摘あります :pray:

2024-06-11 06:50 UTC, meganetaaan commented on docs/assembly_ja.md
> +**青色のラインは切りかけの位置を明示的に図示したものなので、実際のサーボモータに描かれていません**
表記ゆれがあります。

- 切りかけ
- 切り欠け
- 切り欠き

一般的な「切り欠き」に統一しましょう。

2024-06-11 06:50 UTC, meganetaaan commented on docs/images/assembly/disassembling_servo.jpg
改変後の単語にtypo

not use -> not used

2024-06-17 05:07 UTC, KuraZuzu commented on docs/assembly_ja.md
> +**青色のラインは切りかけの位置を明示的に図示したものなので、実際のサーボモータに描かれていません**
切り欠きに統一しました。

2024-06-17 05:07 UTC, KuraZuzu commented on docs/images/assembly/disassembling_servo.jpg
`not used`に統一しました。

2024-06-19 02:03 UTC, meganetaaan approved these changes
LGTMです！

2024-06-19 05:00 UTC, merged